version: '3.8'

services:
  go:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    ports:
      - 8765:8000
    volumes:
      - ../configs/config.yml:/app/configs/config.yml
    tty: true
